# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='notes',
            new_name='post',
        ),
    ]
