# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0004_auto_20170918_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
