# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papp', '0005_auto_20171018_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cmt', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('cmt_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papp.info')),
            ],
        ),
    ]
